### ISSUE TITLE
Login credentials to DiMe should be asked less frequently

### ISSUE THREAD

**Issue by jmakoske** [HIIT/dime-server#16]
There's also a "remember me" checkbox but it doesn't seem to help.

**Comment by chenhunghan** [comment]
@mvsjober I have implemented this in the new-ui, perhaps it could be added to the milestone? 

The behavior is: by checking "remember me" checkbox in login page(/login), it will save base64-encoded username:password to the local-storage of browsers, the token will be saved until users trigger log-out, it will then clean up the credentials in the local-storage.
