### ISSUE TITLE
Dime browser extension text content is practically garbage

### ISSUE THREAD

**Issue by superkai** [HIIT/dime-server#52]
Most Dime browser extenstion text content part is garbage because it does not show wysiwyg the page nor more than first parts of the text content which is in most pages completely irrelevant. The browser extension should have more intelligence to show more relevant extracts from the page or then the text content visualisation should be changed in radical way. 

We need to change things.

**Comment by mvsjober** [comment]
I think this issues is now fixed thanks to the [new browser extension](https://github.com/HIIT/dime-webextension).
