### ISSUE TITLE
Get multiple events by filtering "after" & "before"

### ISSUE THREAD

**Issue by chenhunghan** [HIIT/dime-server#54]
In Wiki, at [here](https://github.com/HIIT/dime-server/wiki/API#get-multiple-events-by-filtering), it says "the time stamp format is the same as for the start and end properties of the Data objects" and the [start and end properties should be interpreted by the Jackson JSON parser](https://github.com/HIIT/dime-server/wiki/Data#common-fields-1) which supports Epoch timestamp or ISO-8601.

However, I tried GET multiple events by filtering **after** & **before** in **Epoch timestamp** and **ISO 8601**

1. Time format in **Unix Offset**, i.e., the number of milliseconds since the Unix Epoch  e.g. `GET <SERVER_HOST>/api/data/events?before=1456071684693&after=1455294084696
` 
2. **ISO 8601 String**. `GET  /api/data/events?before=2016-02-21T16:26:40.452Z&after=2016-02-12T16:26:40.454Z`

but both requests will return the same null error object and a response body: 

`'{"timestamp":1456158574603,"status":400,"error":"Bad Request","exception":"fi.hiit.dime.AuthorizedController$BadRequestException","message":"Invalid arguments","path":"/api/data/events"}' }
`

Not sure what is the proper format of the API call. Add an example in Wiki? 
Thanks.

**Comment by mvsjober** [comment]
Hi @chenhunghan! 

What version of DiMe are you using? The time-based filtering requires the newest version of DiMe directly from the git repository. If you have installed DiMe from the `dime-0.1.zip` file it will be too old.

**Comment by chenhunghan** [comment]
update to latest commit and it works! thanks.
