### ISSUE TITLE
API for removing validated/suggested events

### ISSUE THREAD

**Issue by mvsjober** [HIIT/dime-server#70]

**Comment by chenhunghan** [comment]
I suppose it should be something like this:

Add a validated event  `POST /api/profile/:id/validatedEvent` remove validated event(de-validated) ` DELETE /api/profile/:id/validatedEvent `

Add a suggested event `POST /api/profile/:id/suggestedEvent` remove a suggested  event  ` DELETE /api/profile/:id/suggestedEvent `

**Comment by chenhunghan** [comment]
And there should be API in the same format for documents as well :)

**Comment by mvsjober** [comment]
This is implemented now as of commit eb363d0c76c756a64a2d0725a9c763d380723e54. The DELETE is in fact to the endpoint `/api/profiles/:id/validatedevents/:rid`, where the "rid" is the id of the "event relation" that you get when uploading it. (Event relation is the class defining the weighted relation between the profile and the event, i.e. the object you are uploading with POST.)

I also changed all endpoints to be in plural form, following #75.

As of commit 26c7e7a69883870dcdda13175fe7062eb77aecd3 you can also do a GET to the `/api/profiles/:id/validatedevents` to get the full list if you need it :-)
