### ISSUE TITLE
Request method 'DELETE' not supported

### ISSUE THREAD

**Issue by YiChenAalto** [HIIT/dime-server#78]
I'm trying to use delete event API, and used the method :delete. But get the response:
WARN 25388 --- [nio-8081-exec-2] o.s.web.servlet.PageNotFound             : Request method 'DELETE' not supported

**Comment by mvsjober** [comment]
Hello,

Event deletion should work (I for example have a unit test that does it).

Did you use the correct API endpoint? For example `api/data/event/42`if the event's id=42.

**Comment by YiChenAalto** [comment]
Thanks, Mats. The problem is solved. I wasn't using the correct format, I was sending id in a params object

**Comment by mvsjober** [comment]
OK, no problem. The API is a bit confusing in that sense. DELETE is using the "proper way", while for example modifying existing items uses the "old way" of using the id in the JSON.
