### ISSUE TITLE
UI not showing any events, or documents

### ISSUE THREAD

**Issue by agisbrec** [HIIT/dime-server#79]
Hi,

the DiMe user interface does not show any events, documents or profiles for me. I can see the DiMe logo and the "count me" button, dropdown menu for events/docs/etc, search field and the active user / log out button. I can access my stuff with the API, so DiMe is not empty (e.g. http://localhost:8080/api/profiles).

If it helps, I'm on linux and using Firefox.

DiMe prints:
`Find query: select e from InformationElement e where e.user.id=:userId order by timeModified desc Page: 0 Limit: 24
  param: userId = 3`

Browser console says:
`uncaught at r 
 at i 
 at a 
 a/<@http://localhost:8080/0.5260149f3fa68b062888.chunk.js:1:24518
o@http://localhost:8080/main.87c6fc99d017caa33e60.js:48:25534
f/<@http://localhost:8080/main.87c6fc99d017caa33e60.js:48:26941
s/</e[t]@http://localhost:8080/main.87c6fc99d017caa33e60.js:48:25710
x@http://localhost:8080/main.87c6fc99d017caa33e60.js:25:28090
l@http://localhost:8080/main.87c6fc99d017caa33e60.js:26:1167
A@http://localhost:8080/main.87c6fc99d017caa33e60.js:25:30655
S@http://localhost:8080/main.87c6fc99d017caa33e60.js:25:29473
x@http://localhost:8080/main.87c6fc99d017caa33e60.js:25:28155
n@http://localhost:8080/main.87c6fc99d017caa33e60.js:25:28830
O/u@http://localhost:8080/main.87c6fc99d017caa33e60.js:25:29970
t@http://localhost:8080/main.87c6fc99d017caa33e60.js:5:3981
i/a<@http://localhost:8080/main.87c6fc99d017caa33e60.js:5:4840
t@http://localhost:8080/main.87c6fc99d017caa33e60.js:5:3573
e/</<@http://localhost:8080/main.87c6fc99d017caa33e60.js:48:19591
r/</</l.dispatch@http://localhost:8080/main.87c6fc99d017caa33e60.js:48:22743
T/<@http://localhost:8080/main.87c6fc99d017caa33e60.js:25:30147
r.flush@http://localhost:8080/main.87c6fc99d017caa33e60.js:48:19263
r@http://localhost:8080/main.87c6fc99d017caa33e60.js:48:19149
T@http://localhost:8080/main.87c6fc99d017caa33e60.js:25:30107
S@http://localhost:8080/main.87c6fc99d017caa33e60.js:25:29330
x@http://localhost:8080/main.87c6fc99d017caa33e60.js:25:28155
n@http://localhost:8080/main.87c6fc99d017caa33e60.js:25:28830
  main.87c6fc99d017caa33e60.js:1:27608
TypeError: e.type is undefined`

**Comment by chenhunghan** [comment]
I suppose you have an event/informationElement storing in dime-server that does not have "type"?

**Comment by mvsjober** [comment]
I suppose the problem would have to be with one of the first 24 InformationElements? (Looking at the SQL query from DiMe.)

**Comment by agisbrec** [comment]
Yes, we are creating some events with not many fields.
`{"@type":"SearchEvent","id":106,"timeCreated":1480439563452,"timeModified":1481126330435,"user":{"id":3,"username":"testuser","role":"USER","userId":"fb9e3142-f29a-4050-b312-66d3b12eb84d"},"tags":[{"@type":"Tag","id":15511,"text":"bla","time":1481126330434,"auto":true,"actor":"DiMe Lucene","weight":1.0}],"profileIds":[],"actor":"MemEx","start":1480439563346,"end":1480439563346,"duration":0.0,"query":"bla"}`

**Comment by mvsjober** [comment]
I guess the proper solution is for the UI to test if "type" exists or not. If not, have some fall-back.

**Comment by chenhunghan** [comment]
Yes, @agisbrec @mvsjober  I have added safer property access to prevent this in this commit https://github.com/HIIT/dime-server/commit/26236faa1c388a8cd215521337c64e4c186b2248 

If you are working on the master, please ` git submodule update --remote` and `make run` again.

**Comment by mvsjober** [comment]
Or just `git pull` and `make run` now since I committed the updated submodule reference.

**Comment by agisbrec** [comment]
Seems to be working. Thanks!

**Comment by chenhunghan** [comment]
👍 Thanks for reporting.
