### ISSUE TITLE
partial modification of profile will loss data in other fields

### ISSUE THREAD

**Issue by YiChenAalto** [HIIT/dime-server#82]
When I want to update only the intent filed of a profile, it seems all other fields are re-written. For example, the fields that I did not provide in the request are emptied, previously stored information such as validatedinformationelements or name of the profile will be lost.

**Comment by mvsjober** [comment]
Yes, this is how the API works for now. There is no partial modification. You need to first download the profile, modify the intent and upload it back.

**Comment by YiChenAalto** [comment]
Thanks Matts, we will modify our code
